version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1998"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - test_network
  #SpringBoot项目服务
  tianyianquan:
    container_name: tianyianquan
    #构建指定目录下的Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      - test_network
networks:
  test_network:
    driver: bridge