version: '3.8'
services:
  tianyianquan_mysql:
    container_name: tianyianquan_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "1998"
    restart: always
    networks:
      - test_network
  #SpringBoot项目服务
  tianyianquan:
    working_dir: /tianyianquan
    container_name: tianyianquan_web
    #构建指定目录下的Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tianyianquan/
    depends_on:
      - tianyianquan_mysql
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      - test_network
networks:
  test_network:
    driver: bridge