spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/tianyianquan?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1998
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile:
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: hL7&n9oP2#sQ5$uI8%mZ
    key-store-type: PKCS12
    key-alias: tianyianquan
