spring:
  profiles: pro
  datasource:
    name: test
    url: jdbc:mysql://mysqldb:3306/tianyianquan?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1998
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080